import type { ListingDetailResponse } from "@/types";

/**
 * Mock listings for development — matches ListingDetailResponse from backend exactly.
 * Replace with real API calls once the backend is populated.
 */
export const mockListings: ListingDetailResponse[] = [
  {
    id: 1,
    rent_per_room: 725,
    rent_total: 2175,
    lease_type: "12_month",
    move_in_date: "2026-09-01",
    is_sublet: false,
    sublet_start_date: null,
    sublet_end_date: null,
    gender_preference: "any",
    status: "active",
    view_count: 245,
    created_at: "2026-01-15T10:30:00",
    property_id: 1,
    title: "Cozy Townhouse on College Ave",
    address: "118 College Ave W, Guelph",
    property_type: "townhouse",
    total_rooms: 3,
    bathrooms: 2,
    is_furnished: true,
    has_parking: false,
    has_laundry: true,
    utilities_included: false,
    estimated_utility_cost: 45,
    distance_to_campus_km: 0.4,
    walk_time_minutes: 5,
    bus_time_minutes: null,
    landlord_id: 1,
    landlord_name: "Sarah Mitchell",
    landlord_verified: true,
  },
  {
    id: 2,
    rent_per_room: 650,
    rent_total: 1300,
    lease_type: "12_month",
    move_in_date: "2026-09-01",
    is_sublet: false,
    sublet_start_date: null,
    sublet_end_date: null,
    gender_preference: "any",
    status: "active",
    view_count: 312,
    created_at: "2026-01-20T14:15:00",
    property_id: 2,
    title: "Sunny 2BR near Stone Rd Mall",
    address: "45 Stone Rd W, Unit 302, Guelph",
    property_type: "apartment",
    total_rooms: 2,
    bathrooms: 1,
    is_furnished: false,
    has_parking: true,
    has_laundry: false,
    utilities_included: false,
    estimated_utility_cost: 55,
    distance_to_campus_km: 1.2,
    walk_time_minutes: 12,
    bus_time_minutes: 5,
    landlord_id: 2,
    landlord_name: "David Chen",
    landlord_verified: true,
  },
  {
    id: 3,
    rent_per_room: 680,
    rent_total: 680,
    lease_type: "8_month",
    move_in_date: "2027-01-01",
    is_sublet: false,
    sublet_start_date: null,
    sublet_end_date: null,
    gender_preference: null,
    status: "active",
    view_count: 134,
    created_at: "2026-02-01T09:00:00",
    property_id: 3,
    title: "Bright Studio on Gordon St",
    address: "220 Gordon St, Unit 4B, Guelph",
    property_type: "apartment",
    total_rooms: 1,
    bathrooms: 1,
    is_furnished: true,
    has_parking: false,
    has_laundry: false,
    utilities_included: true,
    estimated_utility_cost: null,
    distance_to_campus_km: 0.5,
    walk_time_minutes: 6,
    bus_time_minutes: null,
    landlord_id: 1,
    landlord_name: "Sarah Mitchell",
    landlord_verified: true,
  },
  {
    id: 4,
    rent_per_room: 550,
    rent_total: 2200,
    lease_type: "12_month",
    move_in_date: "2026-09-01",
    is_sublet: false,
    sublet_start_date: null,
    sublet_end_date: null,
    gender_preference: null,
    status: "active",
    view_count: 89,
    created_at: "2026-02-10T16:45:00",
    property_id: 4,
    title: "Renovated Bungalow on Harvard",
    address: "33 Harvard Rd, Guelph",
    property_type: "house",
    total_rooms: 4,
    bathrooms: 2,
    is_furnished: false,
    has_parking: true,
    has_laundry: true,
    utilities_included: false,
    estimated_utility_cost: 60,
    distance_to_campus_km: 2.5,
    walk_time_minutes: 18,
    bus_time_minutes: 8,
    landlord_id: 3,
    landlord_name: "Mike Patterson",
    landlord_verified: false,
  },
  {
    id: 5,
    rent_per_room: 875,
    rent_total: 4375,
    lease_type: "12_month",
    move_in_date: "2026-09-01",
    is_sublet: false,
    sublet_start_date: null,
    sublet_end_date: null,
    gender_preference: null,
    status: "active",
    view_count: 198,
    created_at: "2026-01-25T11:20:00",
    property_id: 5,
    title: "Spacious House near Campus",
    address: "87 Edinburgh Rd S, Guelph",
    property_type: "house",
    total_rooms: 5,
    bathrooms: 3,
    is_furnished: false,
    has_parking: true,
    has_laundry: true,
    utilities_included: false,
    estimated_utility_cost: 50,
    distance_to_campus_km: 0.7,
    walk_time_minutes: 8,
    bus_time_minutes: null,
    landlord_id: 2,
    landlord_name: "David Chen",
    landlord_verified: true,
  },
  {
    id: 6,
    rent_per_room: 750,
    rent_total: 2250,
    lease_type: "12_month",
    move_in_date: "2026-09-01",
    is_sublet: false,
    sublet_start_date: null,
    sublet_end_date: null,
    gender_preference: null,
    status: "active",
    view_count: 156,
    created_at: "2026-02-05T13:30:00",
    property_id: 6,
    title: "Modern Apartment with Balcony",
    address: "415 Gordon St, Unit B, Guelph",
    property_type: "apartment",
    total_rooms: 3,
    bathrooms: 1,
    is_furnished: false,
    has_parking: false,
    has_laundry: true,
    utilities_included: false,
    estimated_utility_cost: 40,
    distance_to_campus_km: 0.9,
    walk_time_minutes: 10,
    bus_time_minutes: 4,
    landlord_id: 3,
    landlord_name: "Mike Patterson",
    landlord_verified: false,
  },
  {
    id: 7,
    rent_per_room: 620,
    rent_total: 1860,
    lease_type: "8_month",
    move_in_date: "2026-05-01",
    is_sublet: false,
    sublet_start_date: null,
    sublet_end_date: null,
    gender_preference: null,
    status: "active",
    view_count: 67,
    created_at: "2026-02-12T08:00:00",
    property_id: 7,
    title: "Charming Duplex with Yard",
    address: "90 Suffolk St W, Guelph",
    property_type: "townhouse",
    total_rooms: 3,
    bathrooms: 1,
    is_furnished: false,
    has_parking: false,
    has_laundry: false,
    utilities_included: false,
    estimated_utility_cost: 50,
    distance_to_campus_km: 1.8,
    walk_time_minutes: 15,
    bus_time_minutes: 6,
    landlord_id: 1,
    landlord_name: "Sarah Mitchell",
    landlord_verified: true,
  },
  {
    id: 8,
    rent_per_room: 780,
    rent_total: 1560,
    lease_type: "12_month",
    move_in_date: "2026-09-01",
    is_sublet: false,
    sublet_start_date: null,
    sublet_end_date: null,
    gender_preference: null,
    status: "active",
    view_count: 203,
    created_at: "2026-02-08T15:00:00",
    property_id: 8,
    title: "New Build near Kortright",
    address: "150 Kortright Rd W, Unit 210, Guelph",
    property_type: "apartment",
    total_rooms: 2,
    bathrooms: 1,
    is_furnished: true,
    has_parking: true,
    has_laundry: true,
    utilities_included: true,
    estimated_utility_cost: null,
    distance_to_campus_km: 2.8,
    walk_time_minutes: 22,
    bus_time_minutes: 10,
    landlord_id: 2,
    landlord_name: "David Chen",
    landlord_verified: true,
  },
];

/** Mock health scores keyed by listing ID */
export const mockHealthScores: Record<number, number> = {
  1: 88,
  2: 92,
  3: 79,
  4: 86,
  5: 95,
  6: 81,
  7: 73,
  8: 91,
};

/** Latitude/Longitude for each mock listing (Guelph area) */
export const mockCoordinates: Record<number, { lat: number; lng: number }> = {
  1: { lat: 43.5310, lng: -80.2262 }, // College Ave
  2: { lat: 43.5380, lng: -80.2480 }, // Stone Rd
  3: { lat: 43.5305, lng: -80.2290 }, // Gordon St
  4: { lat: 43.5180, lng: -80.2400 }, // Harvard Rd
  5: { lat: 43.5285, lng: -80.2310 }, // Edinburgh Rd
  6: { lat: 43.5340, lng: -80.2350 }, // Gordon St further
  7: { lat: 43.5230, lng: -80.2520 }, // Suffolk St
  8: { lat: 43.5190, lng: -80.2280 }, // Kortright Rd
};
